- hosts: webserver
  become: true
  tasks:
    - name: Installer Docker et Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Télécharger les images depuis DockerHub
      command: |
        docker pull nesrinebenrefifa/todo-frontend:latest
        docker pull nesrinebenrefifa/todo-backend:latest

    - name: Lancer les conteneurs avec Docker Compose
      shell: docker-compose -f /app/docker-compose.yml up -d
